# This file is generated by gyp; do not edit.

export builddir_name ?= /Users/kazupon/Projects/opensource/libuv-lua/tools/gyp/test/copies/src/out
.PHONY: all
all:
	$(MAKE) copies_recursive_trailing_slash copies_recursive_trailing_slash_in_product_dir
