# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := copies_recursive
### Generated for copy rule.
$(builddir)/copies-out/directory: TOOLSET := $(TOOLSET)
$(builddir)/copies-out/directory: directory FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/copies-out/directory
copies_recursive_copies = $(builddir)/copies-out/directory

### Rules for final target.
# Build our special outputs first.
$(obj).target/copies_recursive.stamp: | $(copies_recursive_copies)

# Preserve order dependency of special output on deps.
$(copies_recursive_copies): | 

$(obj).target/copies_recursive.stamp: TOOLSET := $(TOOLSET)
$(obj).target/copies_recursive.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/copies_recursive.stamp
# Add target alias
.PHONY: copies_recursive
copies_recursive: $(obj).target/copies_recursive.stamp

# Add target alias to "all" target.
.PHONY: all
all: copies_recursive

