# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := copies_recursive_trailing_slash
### Generated for copy rule.
$(builddir)/copies-out-slash/directory: TOOLSET := $(TOOLSET)
$(builddir)/copies-out-slash/directory: directory FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/copies-out-slash/directory
copies_recursive_trailing_slash_copies = $(builddir)/copies-out-slash/directory

### Rules for final target.
# Build our special outputs first.
$(obj).target/copies_recursive_trailing_slash.stamp: | $(copies_recursive_trailing_slash_copies)

# Preserve order dependency of special output on deps.
$(copies_recursive_trailing_slash_copies): | 

$(obj).target/copies_recursive_trailing_slash.stamp: TOOLSET := $(TOOLSET)
$(obj).target/copies_recursive_trailing_slash.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/copies_recursive_trailing_slash.stamp
# Add target alias
.PHONY: copies_recursive_trailing_slash
copies_recursive_trailing_slash: $(obj).target/copies_recursive_trailing_slash.stamp

# Add target alias to "all" target.
.PHONY: all
all: copies_recursive_trailing_slash

