# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := copies_recursive_depth
### Generated for copy rule.
$(builddir)/copies-out/subdir: TOOLSET := $(TOOLSET)
$(builddir)/copies-out/subdir: parentdir/subdir FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/copies-out/subdir
copies_recursive_depth_copies = $(builddir)/copies-out/subdir

### Rules for final target.
# Build our special outputs first.
$(obj).target/copies_recursive_depth.stamp: | $(copies_recursive_depth_copies)

# Preserve order dependency of special output on deps.
$(copies_recursive_depth_copies): | 

$(obj).target/copies_recursive_depth.stamp: TOOLSET := $(TOOLSET)
$(obj).target/copies_recursive_depth.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/copies_recursive_depth.stamp
# Add target alias
.PHONY: copies_recursive_depth
copies_recursive_depth: $(obj).target/copies_recursive_depth.stamp

# Add target alias to "all" target.
.PHONY: all
all: copies_recursive_depth

