# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := copies_null
### Generated for copy rule.
copies_null_copies = 

### Rules for final target.
# Build our special outputs first.
$(obj).target/copies_null.stamp: | $(copies_null_copies)

# Preserve order dependency of special output on deps.
$(copies_null_copies): | 

$(obj).target/copies_null.stamp: TOOLSET := $(TOOLSET)
$(obj).target/copies_null.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/copies_null.stamp
# Add target alias
.PHONY: copies_null
copies_null: $(obj).target/copies_null.stamp

# Add target alias to "all" target.
.PHONY: all
all: copies_null

