# This file is generated by gyp; do not edit.

export builddir_name ?= /Users/kazupon/Projects/opensource/libuv-lua/tools/gyp/test/copies/src/out
.PHONY: all
all:
	$(MAKE) copies_null copies1 copies_recursive copies_recursive_depth copies2
