# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := copies1
### Generated for copy rule.
copies-out/file1: TOOLSET := $(TOOLSET)
copies-out/file1: file1 FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += copies-out/file1
copies1_copies = copies-out/file1

### Rules for final target.
# Build our special outputs first.
$(obj).target/copies1.stamp: | $(copies1_copies)

# Preserve order dependency of special output on deps.
$(copies1_copies): | 

$(obj).target/copies1.stamp: TOOLSET := $(TOOLSET)
$(obj).target/copies1.stamp:  FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/copies1.stamp
# Add target alias
.PHONY: copies1
copies1: $(obj).target/copies1.stamp

# Add target alias to "all" target.
.PHONY: all
all: copies1

