# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := copies_recursive_trailing_slash_in_product_dir
### Generated for copy rule.
$(builddir)/copies-out-slash-2/directory: TOOLSET := $(TOOLSET)
$(builddir)/copies-out-slash-2/directory: $(builddir)/copies-out-slash/directory FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/copies-out-slash-2/directory
copies_recursive_trailing_slash_in_product_dir_copies = $(builddir)/copies-out-slash-2/directory

### Rules for final target.
# Build our special outputs first.
$(obj).target/copies_recursive_trailing_slash_in_product_dir.stamp: | $(copies_recursive_trailing_slash_in_product_dir_copies)

# Preserve order dependency of special output on deps.
$(copies_recursive_trailing_slash_in_product_dir_copies): | $(obj).target/copies_recursive_trailing_slash.stamp

$(obj).target/copies_recursive_trailing_slash_in_product_dir.stamp: TOOLSET := $(TOOLSET)
$(obj).target/copies_recursive_trailing_slash_in_product_dir.stamp: $(obj).target/copies_recursive_trailing_slash.stamp FORCE_DO_CMD
	$(call do_cmd,touch)

all_deps += $(obj).target/copies_recursive_trailing_slash_in_product_dir.stamp
# Add target alias
.PHONY: copies_recursive_trailing_slash_in_product_dir
copies_recursive_trailing_slash_in_product_dir: $(obj).target/copies_recursive_trailing_slash_in_product_dir.stamp

# Add target alias to "all" target.
.PHONY: all
all: copies_recursive_trailing_slash_in_product_dir

